package it.frared.prestashop.model;

public enum OrderStatus {

	PAGAMENTO_ACCETTATO,
	PREPARAZIONE_IN_CORSO,
	SPEDITO,
	CONSEGNATO,
	ANNULLATO,
	IN_ATTESA_ACQUISIZIONE,
	INVIATO_A_GESTIONALE,
	ERRORE_INVIO_GESTIONALE,
	INDIRIZZO_NON_VALIDO,
	IN_ATTESA_RITIRO,
	SPEDIZIONE_IN_ERRORE,
	RITIRATO_IN_SEDE,
	IN_TRANSITO,
	FATTURA_NON_CONTABILIZZATA,
	FATTURA_NON_EMESSA,
	ORDINE_GESTIONALE_NON_TROVATO;
}